export const API_MESSAGES = {
  GENERAL: {
    UNAUTHORIZED: "Please login to continue.",
    FORBIDDEN: "You don't have permission to perform this action.",
    BAD_REQUEST: "Invalid request. Please check your input and try again.",
    TOO_MANY_REQUESTS: "Too many requests. Please try again later.",
    INPUT_VALIDATION_FAILED: "Please check your input and fix any errors.",
    QSTASH: {
      INVALID_SIGNATURE: "Invalid request signature. Access denied.",
    },
  },
  AUTH: {
    REQUEST_RESET_PASSWORD: "Password reset link has been sent to your email.",
    METADATA: "Auth metadata loaded successfully.",
    BAN: "User has been banned successfully.",
    UNBAN: "User has been unbanned successfully.",
  },
  NOTIFICATION: {
    GET_NOTIFICATIONS: "Notifications loaded successfully.",
    GET_SETTINGS: "Notification settings loaded successfully.",
    UPDATE_SETTINGS: "Notification settings updated successfully.",
    MARK_AS_READ: "Notification marked as read.",
    SUBSCRIBE_PUSH: "Successfully subscribed to push notifications.",
    UNSUBSCRIBE_PUSH: "Successfully unsubscribed from push notifications.",
  },
  USER: {
    GET_ALL: "Users loaded successfully.",
    GET_STATS: "User statistics loaded successfully.",
    GET_DETAILS: "User details loaded successfully.",
    GET_ALL_FOR_SEARCH: "Users loaded successfully.",
    PROFILE_UPDATE: "Profile updated successfully.",
    UPDATE: "User updated successfully.",
    NOT_FOUND: "User not found.",
    NOT_MATCHED: "User information doesn't match our records.",
    EXPORT: "Users data exported successfully.",
    PERMISSION: {
      GET_ALL: "Permissions loaded successfully.",
    },
    ROLE: {
      GET_ALL: "Roles loaded successfully.",
      CREATE: "Role created successfully.",
      EXIST: "Role already exists.",
      DELETE: "Role deleted successfully.",
      UPDATE: "Role updated successfully.",
      NOT_FOUND: "Role not found.",
    },
  },
  UPLOAD: {
    GET_SIGNED_URL: "Upload URL generated successfully.",
    GET_DOWNLOAD_URL: "Download URL generated successfully.",
    CONFIRM_UPLOAD: "Upload confirmed successfully.",
    ASSIGN_ENTITY: "File attached successfully.",
    DELETE: "File deleted successfully.",
    NOT_CREATE: "Failed to create upload. Please try again.",
    NOT_FOUND: "File not found.",
  },
  TASK: {
    GET_ALL: "Tasks loaded successfully.",
    GET_DETAILS: "Task details loaded successfully.",
    CREATE: "Task created successfully.",
    UPDATE: "Task updated successfully.",
    UPDATE_STATUS: "Task status updated successfully.",
    DELETE: "Task deleted successfully.",
    DELETE_ALL: "All selected tasks deleted successfully.",
    NOT_FOUND: "Task not found.",
    NOT_CREATE: "Failed to create task. Please try again.",
    NOT_UPDATE: "Failed to update task. Please try again.",
    NOT_ALLOWED: "You don't have permission to manage this task.",
    ASSIGNEE_NOT_IN_ORG:
      "The selected assignee is not a member of this organization.",
  },
  CONTACT: {
    GET_ALL: "Contacts loaded successfully",
    GET_DETAILS: "Contact details loaded successfully",
    NOT_FOUND: "Contact not found",
    REPLY_CREATED: "Reply sent successfully",
  },
};
