import type { IncomingMessage, ServerResponse } from "node:http";

import MainHelmet, { type HelmetOptions } from "helmet";

import type { IResponse } from "../types";

export type HelmetMiddlewareConfig = Readonly<HelmetOptions>;

/**
 * Emits the per-request CSP nonce generated by `nonceMiddleware`, falling back
 * to `'self'` when no nonce is present.
 */
function nonceDirective(_req: IncomingMessage, res: ServerResponse): string {
  const nonce = (res as IResponse).locals?.cspNonce;
  return nonce ? `'nonce-${nonce}'` : "'self'";
}

export function helmetMiddleware(configs?: HelmetMiddlewareConfig) {
  return MainHelmet({
    contentSecurityPolicy: {
      directives: {
        defaultSrc: ["'self'"],
        scriptSrc: ["'self'", nonceDirective, "https://cdn.jsdelivr.net"],
        styleSrc: ["'self'", nonceDirective, "https://cdn.jsdelivr.net"],
        imgSrc: ["'self'", "data:", "https:"],
        fontSrc: ["'self'", "https:", "data:"],
        connectSrc: ["'self'"],
        frameSrc: ["'none'"],
        objectSrc: ["'none'"],
        baseUri: ["'self'"],
        formAction: ["'self'"],
        frameAncestors: ["'self'"],
      },
    },
    crossOriginEmbedderPolicy: false,
    ...configs,
  });
}
