import { formatError } from "../../utils";
import { BullmqError } from "./BullmqError";
import { signBullmqPayload } from "./signature";
import type {
  BullmqBatchEnqueueResult,
  BullmqClientServiceConfig,
  BullmqEnqueueBatchRequest,
  BullmqEnqueueOptions,
  BullmqEnqueueRequest,
  BullmqEnqueueResult,
  IBullmqPublisher,
} from "./types";

/** Configuration after defaults have been applied. */
type ResolvedConfig = BullmqClientServiceConfig & { defaultRetries: number };

/** Public surface shared by every BullMQ producer. */
export interface IBullmqClientService {
  /** Sign an arbitrary payload with the configured secret. */
  signPayload(payload: unknown): string;
  /** Access the transport used to reach the backend broker. */
  getPublisher(): IBullmqPublisher;
}

/** Default number of delivery attempts when the caller does not set one. */
const DEFAULT_BULLMQ_RETRIES = 3;

/**
 * Lean BullMQ producer.
 *
 * Responsibilities:
 * - sign the job payload with the shared HMAC secret;
 * - hand the enqueue request to an app-supplied {@link IBullmqPublisher} that
 *   calls the matching backend queue contract;
 * - verify inbound request signatures.
 *
 * Unlike a QStash wrapper it holds no message logs, dead-letter queue or
 * callback registry: BullMQ persists jobs and retries them, and both apps share
 * the same database.
 */
export class BullmqClientService implements IBullmqClientService {
  private readonly config: ResolvedConfig;
  private readonly publisher: IBullmqPublisher;

  constructor(bullmqConfig: BullmqClientServiceConfig) {
    if (!bullmqConfig.signingSecret) {
      throw new BullmqError(
        "A signing secret is required to sign and verify BullMQ jobs",
        "BULLMQ_CONFIG_INVALID",
        500
      );
    }

    this.config = {
      ...bullmqConfig,
      defaultRetries: bullmqConfig.defaultRetries ?? DEFAULT_BULLMQ_RETRIES,
    };
    this.publisher = this.config.publisher;
  }

  /** Generate a unique job id for an enqueue. */
  private generateJobId(): string {
    return `job_${Date.now()}_${Math.random().toString(36).slice(2, 10)}`;
  }

  /**
   * Sign and enqueue a job. `jobId` is generated by the producer so the
   * backend can use it as the BullMQ job id (deduplicating re-sends).
   */
  protected async enqueue<T>(
    options: BullmqEnqueueOptions<T>
  ): Promise<BullmqEnqueueResult> {
    const request: BullmqEnqueueRequest<T> = {
      queue: options.queue,
      job: options.job,
      payload: options.payload,
      jobId: this.generateJobId(),
      ...(options.retries !== undefined && { retries: options.retries }),
      ...(options.delay !== undefined && { delay: options.delay }),
    };

    try {
      const signature = this.signPayload(request.payload);

      return await this.publisher.enqueue(request, signature);
    } catch (err) {
      throw err instanceof BullmqError
        ? err
        : new BullmqError(formatError(err), "BULLMQ_ENQUEUE_FAILED", 500, {
            queue: options.queue,
            job: options.job,
          });
    }
  }

  /**
   * Sign and enqueue a batch of item payloads in a single transport call.
   *
   * The whole array is signed once; the backend validates and fans it out into
   * individual jobs.
   */
  protected async enqueueBatch<T>(
    options: BullmqEnqueueOptions<T[]>
  ): Promise<BullmqBatchEnqueueResult[]> {
    const payloads = options.payload;

    const request: BullmqEnqueueBatchRequest<T> = {
      queue: options.queue,
      job: options.job,
      payloads,
      jobIds: payloads.map(() => this.generateJobId()),
      ...(options.retries !== undefined && { retries: options.retries }),
      ...(options.delay !== undefined && { delay: options.delay }),
    };

    try {
      const signature = this.signPayload(request.payloads);

      return await this.publisher.enqueueBatch(request, signature);
    } catch (err) {
      throw err instanceof BullmqError
        ? err
        : new BullmqError(formatError(err), "BULLMQ_ENQUEUE_FAILED", 500, {
            queue: options.queue,
            job: options.job,
          });
    }
  }

  /** Sign an arbitrary payload with the configured secret. */
  public signPayload(payload: unknown): string {
    return signBullmqPayload(this.config.signingSecret, payload);
  }

  /** Expose the underlying transport. */
  public getPublisher(): IBullmqPublisher {
    return this.publisher;
  }
}
